version: '3'

services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    expose:
      - "3306"

    environment:
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=db_mydatabase 
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/db_mydatabase?createDatabaseIfNotExist=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=password
    restart: on-failure
