spring.application.name=app

# Conexão com o Banco de Dados (MySQL do Docker)
spring.datasource.url=jdbc:mysql://localhost:3306/db_mydatabase?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=myuser
# Verifique a senha que você definiu no seu arquivo docker-compose.yml
spring.datasource.password=password

# Configurações do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Dialeto para o MySQL 8+ ou 9
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver